language: java
env:
    global:
    - GRADLE_OPTS="-Xmx1024m -Xms256m -XX:MaxPermSize=256m -XX:PermSize=256m"
before_script:
- sudo service postgresql stop || true
- sudo service mysql stop || true
script: ./gradlew --stacktrace compileFrege
